### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zunairkhan811** [fickryiman/Leaderboard#7]
## Hi @fickryiman  🙋‍♂️
Good job working on your first LeaderBoard Project. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement a few on the project but you are almost there!!! 🚶: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

# Required Changes :recycle: 
- You have done things very well but if you kindly Make the whole content in the center, I think it will look more good as that will also be better for a good UI experience.

Cheers, and Happy coding!👏👏👏

**Comment by fickryiman** [comment]
ok, I would like to try your suggestion, to center the whole content.
Here is the result:
![image](https://user-images.githubusercontent.com/116701353/231976449-41bc8121-dffd-4cf7-9536-c8ba2f1554ad.png)
